# 项目相关配置
boot:
  # 名称
  name: boot
  # 版本
  version: 4.0.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/boot/uploadPath，Linux配置 /home/boot/uploadPath）
  profile: C:/waterReport/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 扫描二维码填报个人健康信息地址前缀
  serviceHttpUrl: http://47.108.27.46:8190/app/index/

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8190
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    # post请求数据大小限制（默认2M，小于0则不限制）
    max-http-post-size: -1
# 日志配置
logging:
  level:
    com.boot: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  500MB
       # 设置总上传的文件大小
       max-request-size:  500MB
  # 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
  freemarker:
    allow-request-override: false
    # 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
    allow-session-override: false
    # 是否启用模板缓存。
    cache: false
    # 模板编码。
    charset: UTF-8
    # 是否检查模板位置是否存在。
    check-template-location: true
    # Content-Type value.
    content-type: text/html
    # 是否启用freemarker
    enabled: true
    # 设定所有request的属性在merge到模板的时候，是否要都添加到model中.
    expose-request-attributes: false
    # 是否在merge模板的时候，将HttpSession属性都添加到model中
    expose-session-attributes: false
    # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    expose-spring-macro-helpers: true
    # 是否优先从文件系统加载template，以支持热加载，默认为true
    prefer-file-system-access: true
    # 设定模板的后缀.
    suffix: .ftl
    # 设定模板的加载路径，多个以逗号分隔，默认:
    template-loader-path: classpath:/static/ftl/
    # 设定FreeMarker keys.
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jta:
    atomikos:
      properties:
        recovery:
          forget-orphaned-log-entries-delay:

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.boot
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /admin/login
    # 权限认证失败地址
    unauthorizedUrl: /admin/unauth
    # 首页地址
    indexUrl: /admin/index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: char
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 240
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /admin/system/notice/*
  # 匹配链接
  urlPatterns: /admin/system/*,/admin/monitor/*,/admin/tool/*,/admin/supply/*